#!/usr/bin/env python

from graph import g

def main():
    print('\n The following units are available: \n')
    for unit in g.keys():
        print(unit)
    print('\n')

if __name__ == '__main__':
    main()